# Define common abbreviations and their full forms
abbreviations = {
    "AI": "Artificial Intelligence",
    "KI": "Artificial Intelligence",
    "ML": "Machine Learning",
    "NLP": "Natural Language Processing",
    "NLU": "Natural Language Understanding",
    "LLM": "Large Language Model",
    "LLMs": "Large Language Models",
    "CL": "Computational Linguistics",
    "CV": "Computer Vision",
    "Coxi": "Cognitive Science",
    "CogSci": "Cognitive Science",
    "Philo": "Philosophy",
    "Intro": "Introduction",
    "Scipy": "Scientific Programming in Python",
    "Info": "Informatics",
    "Neuroinfo": "Neuroinformatics",
    "Math": "Mathematics",
    "Neurobio": "Neurobiology",
    "HCI": "Human-Computer-Interactions",
    "MCI": "Mensch-Computer-Interaktion",
    "DL": "deep learning",
    "VR": "virtual reality"
}

# Define examples for each intent-category
intent_examples = {
    "greeting": ["hello", "hi chatbot", "good morning", "how are you", "hola", "hallo", "hey", "moin", "buenos dias"],
    "thanks": ["Thank you", "Thanks", "You helped me, thank you", "Thanks for your help", "Thank you for the recommendations"],
    "free_description": [
        "I'm looking for a course for computational linguistics",
        "I want to find a course about machine learning",
        "Can you recommend me an online course?",
        "I am looking for a beginner course in psychology",
        "I want a course from the module artificial intelligence",
        "I want a course from the module Artificial Intelligence",
        "I want a course about philosophy",
        "I want to learn about natural language processing",
        "I want to know more about natural language processing",
        "I like artificial intelligence",
        "I like computer science",
        "I need 4 ECTS for my Computational Linguistics module",
        "Is there a course with 2 ECTS for the elective Artificial Intelligence module?",
        "I want a Computational Linguistics lecture",
        "I'm looking for a hybrid Computational Linguistics seminar",
        "Are there any courses for the Mathematics module with 4 sws?",
        "I need 2 more ECTS for the Informatics module",
        "I want a hybrid lecture with 2 SWS and 4 ects for the elective computational linguistics module.",
        "I want a course with 4 ECTS.",
        "I want a course with 2 SWS.",
        "I want a course with 6 ECTS.",
        "I want something with 4 SWS.",
        "I need 4 ECTS.",
        "I prefer online lectures",
        "I'm looking for a course for my Computational Linguistics module",
        "I want to learn more about Artificial Intelligence",
        "I want to learn more about Machine Learning",
        "I want to learn more about Computational Linguistics",
        "I want to learn more about Philosophy",
        "I want to learn programming",
        "I like python",
        "I like Machine Learning",
        "I like Neurobiology",
        "I like Computational Linguistics",
        "I like Philosophy",
        "I like math",
        "It should take place on Thursday",
        "It should be on Monday or Wednesday",
        "I like Prof. Dr. Gordon Pipa",
        "I like Pipa",
        "I want a course on Tuesday",
        "Are there any courses on Machine Learning?",
        "Are there any Artificial Intelligence courses on Mondays?",
        "I'm looking for a course that explores the neural mechanisms underlying perception and cognition.",
        "I want to study the role of the brain's structure in decision-making and memory.",
        "Is there a class focusing on the interaction between neural networks and behavior?",
        "I'd like a course that integrates artificial intelligence techniques with cognitive modeling.",
        "I'm interested in how machine learning algorithms simulate human problem-solving.",
        "Are there courses on the ethical implications of AI in cognitive systems?",
        "I'm looking for a course about cognitive biases and how they affect decision-making.",
        "Do you have classes that delve into the psychological aspects of learning and memory?",
        "I want to study how perception and attention are linked in cognitive processes.",
        "I want a course that examines the cognitive foundations of language acquisition.",
        "Is there a class on the interaction between syntax and semantics in human language processing?",
        "I'm looking for a course about how the brain processes and produces language.",
        "I'd like to study philosophical theories about consciousness and mind.",
        "Are there courses on the nature of knowledge and how it relates to cognitive science?",
        "I'm interested in exploring the philosophical implications of artificial intelligence.",
        "I'm looking for a course that focuses on designing interfaces based on cognitive principles.",
        "Is there a class about how humans process information in interaction with technology?",
        "I want to study the cognitive aspects of usability testing.",
        "I'm looking for a course that explores the neural mechanisms underlying perception and cognition, preferably in the mornings.",
        "I want to study the role of the brain's structure in decision-making and memory, ideally in an afternoon class.",
        "Is there a class focusing on the interaction between neural networks and behavior offered in the evenings?",
        "I'd like a course that integrates AI techniques with cognitive modeling, scheduled for late mornings.",
        "I'm interested in how machine learning algorithms simulate human problem-solving, especially if it's a weekend course.",
        "Are there courses on the ethical implications of AI in cognitive systems that meet after 6 PM?",
        "I'm looking for a course about cognitive biases and how they affect decision-making, preferably on weekdays in the afternoon.",
        "Do you have classes that delve into the psychological aspects of learning and memory, available in the early evenings?",
        "I want to study how perception and attention are linked in cognitive processes, ideally in a morning session.",
        "I want a course that examines the cognitive foundations of language acquisition, offered on weekends.",
        "Is there a class on the interaction between syntax and semantics in human language processing that runs late in the afternoon?",
        "I'm looking for a course about how the brain processes and produces language, available in the evenings.",
        "I'd like to study philosophical theories about consciousness and mind, preferably in the early morning.",
        "Are there courses on the nature of knowledge and how it relates to cognitive science, scheduled for late evenings?",
        "I'm interested in exploring the philosophical implications of artificial intelligence, especially on weekends.",
        "I'm looking for a course that focuses on designing interfaces based on cognitive principles, offered in the mornings.",
        "Is there a class about how humans process information in interaction with technology, ideally after 5 PM?",
        "I want to study the cognitive aspects of usability testing, preferably on weekday mornings.",
        "I want a course on neural mechanisms, preferably in the mornings.",
        "Looking for a class on memory and decision-making in the afternoons.",
        "Are there evening classes on neural networks and behavior?",
        "I'd like a morning course on AI and cognitive modeling.",
        "Interested in machine learning for problem-solving, on weekends.",
        "Any AI ethics courses after 6 PM?",
        "Looking for a class on cognitive biases, in the afternoon.",
        "Do you have psychology classes in the early evening?",
        "I want to study perception and attention, in the morning.",
        "A weekend course on language acquisition would be great.",
        "Is there an afternoon class on language processing?",
        "Looking for evening classes on brain processing and language.",
        "I'd like to study consciousness and mind in the mornings.",
        "Are there late evening courses on knowledge and cognitive science?",
        "I'm interested in AI philosophy, especially on weekends.",
        "A course on cognitive principles in the morning would be ideal.",
        "Any technology and cognition classes after 5 PM?",
        "I want a morning class on usability testing.",
        "I'm looking for a course on neural networks with 6 ECTS points.",
        "I want a course in cognitive modeling with at least 4 SWS.",
        "Is there a 5 ECTS class on the brain's role in decision-making?",
        "I'm interested in a 2 SWS class on AI and cognition.",
        "Looking for a course on language processing with 8 ECTS points.",
        "Do you offer a 6 SWS class on cognitive psychology?",
        "I need a 4 ECTS course on machine learning and cognition.",
        "Are there courses with 3 SWS on cognitive biases?",
        "I'd like a class on perception with 5 ECTS points and 2 SWS.",
        "Looking for a 7 ECTS course on consciousness and mind.",
        "Is there a 4 SWS course on cognitive science ethics?",
        "I'd prefer a 3 SWS course on memory systems and decision-making.",
        "Is there a 6 ECTS class on human-computer interaction?",
        "I'm searching for a 5 ECTS course on the philosophy of AI.",
        "I want a class on cognitive development with 2 SWS per week.",
        "Are there 4 SWS classes available on learning and memory?",
        "Looking for a 5 ECTS course on usability testing and cognition.",
        "I want a seminar with recordings.",
        "I want an online lecture",
        "I want a seminar with 4-8 ECTS.",
        "seminar with recordings or online",
        "lecture and practice would be nice",
        "I need a seminar with 4 ECTS for elective AI",
        "Any seminars with 2-4 sws?",
        "I want an online seminar on Tuesday or Thursday from 8 to 10",
        "seminar between Monday and Wednesday from 2 to 4 pm",
        "a hybrid seminar",
        "something online with recordings",
        "an English seminar",
        "Is there a German Seminar on Philosophy of Artificial Intelligence?",
        "Is there a hybrid or online seminar for the elective Philosophy module?",
        "I need something for Artificial Intelligence",
        "I want to learn Python",
        "I want a seminar",
        "Any seminars?",
        "Anything with recordings",
        "Looking for something about Machine learning that has recordings",
        "I want a lecture from Thelen",
        "I want a seminar taught by Bruni",
        "Anything online from Pipa or Pika",
        "a hybrid lecture by Walter",
        "I want 2-4 ects or 6-8 ects",
        "Only lectures",
        "Only courses on wednesdays to fridays",
        "I want a course in person",
        "I want a course on monday",
        "Looking for courses on critical thinking",
        "Searching for courses on ethics of Artificial Intelligence"
    ],
    "liked_course_reference": [
        "I liked the cognitive neuroscience course",
        "I really liked the course Artificial Intelligence and the Web",
        "I enjoyed Philosophy 101",
        "Neurobiology was interesting",
        "Machine Learning 101 was great",
        "Cognitive neuroscience was nice",
        "I liked Introduction to Artificial Intelligence and Logic Programming",
        "I liked Introduction to epistemology and philosophy of science",
        "I really liked 'Introduction to political philosophy'",
        "I enjoyed Introduction to the Ethics of Artificial Intelligence",
        "Introduction to the Philosophy of Mind was great",
        "Introduction to Cognitive (Neuro-)Psychology was nice",
        "Introduction to Computational Linguistics was good",
        "Introduction to Sleep and Dream was interesting",
        "I want something like Introduction to Unity",
        "I want a course like Introduction to Statistics and Data Analysis",
        "I'm looking for a seminar like Neuroscience and Philosophy",
        "I want a lecture similar to Introduction to Logic and Critical Thinking",
        "I really enjoyed the course on cognitive psychology last semester.",
        "The neural networks class I took in the fall was fascinating.",
        "Last semester, I loved the course on artificial intelligence and its applications.",
        "I took a great course on human-computer interaction last semester.",
        "I really enjoyed the philosophy of mind class I had last semester.",
        "The class on language acquisition in the spring was amazing.",
        "I really liked the course on cognitive neuroscience I took last semester.",
        "The AI and machine learning course I did last semester was very insightful.",
        "I had a great time in the course about perception and attention last semester.",
        "Last semester, I enjoyed the philosophy of cognitive science class.",
        "The course on memory systems I took last semester was very interesting.",
        "I really liked the cognitive development course I took last semester.",
        "I loved the human cognition class I took last fall.",
        "The course on cognitive behavior was one of my favorites last semester.",
        "I really enjoyed studying the psychology of decision-making last semester.",
        "The neuropsychology course I took last semester was so engaging.",
        "I found the course on artificial intelligence ethics really insightful last semester.",
        "I really enjoyed the cognitive psychology course.",
        "The neural networks class was fascinating.",
        "I loved the course on artificial intelligence and its applications.",
        "The human-computer interaction course was great.",
        "I really enjoyed the philosophy of mind course.",
        "The class on language acquisition was amazing.",
        "I really liked the cognitive neuroscience course.",
        "The AI and machine learning course was very insightful.",
        "I enjoyed the course on perception and attention.",
        "The philosophy of cognitive science class was excellent.",
        "The memory systems course was very interesting.",
        "I really liked the cognitive development course.",
        "The human cognition class was one of my favorites.",
        "I enjoyed the course on cognitive behavior.",
        "The psychology of decision-making course was very engaging.",
        "The neuropsychology course was very enriching.",
        "I found the course on deep reinforcement learning to be very insightful.",
        "I loved the course on empathy in a digial age.",
        "The class on brain and behavior was really interesting.",
        "I really enjoyed the course about deep learning for image generation.",
        "The artificial intelligence and ethics class was so thought-provoking.",
        "The course on language processing was both challenging and rewarding.",
        "I liked the course on the neuroscience of memory.",
        "The course on cognitive models in artificial intelligence was amazing.",
        "I enjoyed Critical perspectives on AI.",
        "The developmental psychology course was a great experience.",
        "The course on emotion and cognition was very insightful.",
        "I found the class on a theory of moral responsibility extremely engaging.",
        "The cognitive linguistics course was fascinating.",
        "I enjoyed the introduction to computational neuroscience.",
        "The course on human perception and consciousness was enlightening.",
        "I liked the class on reasoning and problem-solving in cognitive science.",
        "The course about learning theories and their applications was really interesting.",
        "The class on cognitive robotics was highly informative.",
        "I liked Introduction to Cognitive Science.",
        "I liked Introduction to Computational Linguistics.",
        "I liked Cognitive Neuroscience and Its Applications.",
        "I liked the Advanced Machine Learning course.",
        "I liked the Philosophy of Mind class.",
        "I liked Artificial Intelligence and the Human Brain.",
        "I liked Cognitive Psychology and Behavior.",
        "I liked the seminar on Human-Computer Interaction.",
        "I liked the Language Acquisition lecture.",
        "I liked Introduction to Artificial Intelligence.",
        "I liked Neuropsychology and Cognitive Disorders.",
        "I liked the course on the Neuroscience of Learning.",
        "I liked the Computational Models of Cognition class.",
        "I liked Introduction to Computational Linguistics.",
        "I liked Cognitive Development.",
        "I liked the lecture Introduction to Cognitive (Neuro-)Psychology.",
        "I liked the lecture Non-classical logic: The basics.",
        "I liked the Action & Cognition: Higher Cognitive Functions course.",
        "I liked the Ethics of Artificial Intelligence class.",
        "I liked the seminar Grundbegriffe der analytischen Philosophie.",
        "I liked Enhancing AI through Hybrid Data Sets.",
        "I liked the seminar on Cognitive Psychology and Education.",
        "I liked Scientific Programming in Python",
        "I liked the course Scientific Programming in Python",
        "I liked Machine Learning"
    ],
    "feedback": [
        "I liked the second course", 
        "The recommendations were not good", 
        "I want more courses like the first one", 
        "I want more courses like the second one", 
        "I want more courses like number three",
        "I like the first recommendation",
        "I like the last one",
        "The third one sounds interesting",
        "Number three sounds good",
        "I like course 4",
        "The fifth one is interesting",
        "I only like number 3",
        "I like the course 2",
        "Course 1 sounds good",
        "Course three is interesting",
        "The final recommendation is interesting",
        "I like the first, third, fourth and fifth one",
        "I like number one, two and five",
        "I like course number 2, 4 and 5",
        "I don't like the first one",
        "Number 2 does not sound interesting",
        "Course 5 is not interesting",
        "Course two sounds not good",
        "The last course doesn't sound good",
        "Your final recommendation does not sound good",
        "The last one is not good",
        "The last course is bad",
        "I dislike the first recommendation",
        "I dislike course 4",
        "I dislike course three",
        "Number five sounds boring",
        "Course 4 sounds boring",
        "Course one, two and three sound boring",
        "Number 1 and 5 sound boring",
        "I don't like 3, 4 and 2",
        "I hate number 3",
        "I hate course two",
        "The first and second one sound good, but I don't like the fifth one",
        "I like all of them",
        "All sound interesting",
        "All of them sound good",
        "I like them all",
        "I like all recommendations",
        "I like every recommended course",
        "Every recommendation is good",
        "I don't like any of them",
        "None of them seem good",
        "None of them are interesting",
        "I like none of them",
        "I like none of the courses",
        "I like none of the recommendations",
        "I hate all of them",
        "I like 1 and 3, but 2, 4 and 5 are boring",
        "Three and four are interesting. Two and five are",
        "I like course five but not four",
        "I dislike number 3 and 5, but not 2",
        "Course three and 4 are good, but 2 is boring",
        "I like the first course. But not the second",
        "I like 1, 3, 5, but not 2 and four",
        "I like courses 2, 3, 4",
        "I like courses 1 and 2",
        "I dislike courses one, two and three"
        ],
    "nonsense": [
        "The frog dances with a blue quantum potato every Thursday.",
        "I want a class on the theory of flying pancakes in space.",
        "Are there any courses on time-traveling zebras and their cognitive abilities?",
        "Looking for a course where trees speak in binary code.",
        "Can I take a class about the cognitive processes of underwater dragons?",
        "I want to learn about the neural pathways of invisible unicorns.",
        "Is there a course on how clouds process information on a rainy day?",
        "Do you offer a course on the psychological effects of eating rainbow-colored sand?",
        "I'm looking for a class that studies the cognition of purple grasshoppers.",
        "Are there courses on the brain's response to abstract jellybeans?",
        "I'm interested in a course about the language of dancing robots.",
        "Looking for a class that teaches how to train talking trees to solve math problems.",
        "I need a course on the logic of flying pizza slices.",
        "Is there a class on understanding the cognitive functions of unicorns?",
        "I want a course on how waffles think during a solar eclipse.",
        "Do you offer a program on the cognitive behavior of time-traveling socks?",
        "I'm looking for a course on the emotional intelligence of robots from Mars.",
        "I need a class on the emotional intelligence of invisible octopuses.",
        "Can you offer a course on the neural networks of flying pigs?",
        "I want to study how clouds communicate with the wind using Morse code.",
        "Is there a course on the cognitive behavior of dancing teapots?",
        "Looking for a class that teaches how to train squirrels to solve puzzles.",
        "Do you offer a program on the psychology of rainbow-colored frogs?",
        "Are there courses on the logic of talking rocks and their decision-making?",
        "I'm interested in learning how to communicate with shadow puppets in binary.",
        "Is there a class on the cognition of time-traveling bananas?",
        "I want to study the memory systems of invisible flamingos.",
        "Do you have a course that explores the behavior of telepathic squirrels?",
        "Looking for a course on the intelligence of jellyfish during a full moon.",
        "Can I take a class about the emotional responses of clouds in the sky?",
        "Are there any courses on the neural pathways of flying toast?",
        "I'm interested in how giraffes understand quantum mechanics.",
        "Is there a class that teaches the cognitive processes of rainbow unicorns?",
        "Can I study the logic of time-traveling pizzas in a course?",
        "I need a course on the psychology of flying waffles.",
        "Can you offer a class about how giraffes communicate with clouds?",
        "Looking for a course on the emotional intelligence of rainbow-colored rocks.",
        "Is there a class on training jellyfish to play chess?",
        "I want to study the behavior of teleporting donuts.",
        "Are there courses on the cognitive abilities of talking cucumbers?",
        "I'm interested in a class on how mushrooms perceive time.",
        "Looking for a course about the cognitive processes of dancing pickles.",
        "I want to learn about the logic of invisible kangaroos.",
        "Are there any classes on how penguins make decisions in zero gravity?",
        "I'm looking for a course about the brain functions of flying spaghetti monsters.",
        "Is there a course on teaching squirrels to meditate?",
        "Can I take a class on the emotional intelligence of singing potatoes?",
        "Are there any courses on how clouds form friendships?",
        "I want a class about the cognitive development of intergalactic jellybeans.",
        "Looking for a course on the psychology of quantum flamingos.",
        "Is there a course that teaches how to communicate with underwater teacups?",
        "I want a course about the war of flowers"
    ],
    "no_info": [
        "I want course recommendations",
        "I like courses",
        "I want a course",
        "I'm looking for a course",
        "I need a new course",
        "I want to find interesting courses for the next seemster",
        "Are there any interesting courses?",
        "I like the university"
    ]

}